version: '3.3'
services:
    app:
        build: .
        ports:
            - 3000:3000
        volumes:
            - "$PWD/apps:/src"
            - node-modules:/src/node_modules
        command: tail -f > /dev/null
        container_name: uasm
volumes: 
    node-modules: